export const iconData =[
  {
    id: "1",
    Code: "ITP",
    Name: "INFORM TERRACE PROJECT",
    Typology: "LANDSCAPING",
    Technology: "RHINO",
    Year: "2014",
    Status: "IDEA",
    Location: "BANGALORE",
    Description:
      "Living at home. Coming back home. Feeling at home. There's no place like home. These expressions are often heard, said, and felt without noticing the strength and importance of the word HOME: the magnitude of the space, the responsibility it carries, and the affection it generates. Our project does nothing but pursue the idea of turning a building into a home. Located in Villa Carlos Paz, a hilly city in the province of Córdoba, surrounded by nature with its rivers, and lake, constantly accompanied by hills that guard the urban area. Here is where our project was born, a building of residential units within a neighborhood adjacent to the city center, which keeps it away from the hustle of tourism and at the same time within an urbanized natural environment. Structured around three blocks built around a central core that dematerializes common circulation, turning stairs and corridors simply into sidewalks, courtyards, and public space, through the development of a brick metal walkway, accompanying the visual rhythm of the corridors. The large and ventilated void becomes an element of climate control, visuals, lights and shadows, encounters, permanence, and tradition. The exterior reminds us of the interior. Spacious, well-ventilated, and illuminated spaces are achieved thanks to a balanced use of environmental resources. The materiality accompanies the site of implantation, relates to the context, and seeks to provide sensory value with textures, organic colors, and imperfect and irregular forms, creating simple atmospheres that go with living at HOME. Flia was designed thinking of conscious spaces, their details, and their functionality. It is a building composed of the sum of 12 houses, with patios, a square, and a parking garage. Flia is a strong concept that deals with good living, sharing, conscious dwelling, recognizing oneself with the environment, integrating with it, and being part of it. We live in society sharing with others and with ourselves: we live in Flia.",
  },
  {
    id: "2",
    Code: "BQH",
    Name: "BOUQUET HOUSE",
    Typology: "HOUSING",
    Technology: "REVIT",
    Year: "2013",
    Status: "COMPLETED",
    Location: "BHUBANESWAR",
    Description:
      "On this humble inter-terrace site of under 1400sqft, the architects have managed to create a sensation of surprising openness and limitless space within a lush green environment, while still very comfortably accommodating all the necessary functions of a home. Situated within the narrow streets and densely packed rows of terrace houses of Opera Estate, it is difficult to imagine that such an open and well-ventilated house could be achievable. But through clever design and the immersion of natural greenery throughout both the internal and external spaces of the house, the feeling within the home is one of being encompassed by a boundless garden, with a gentle, constant breeze. To achieve this sense of spaciousness, the architects have tucked all the main service areas of the home away into a part basement, leaving the ground floor as a vast open space with a central courtyard. In this triple volume courtyard grows a leafy ficus tree within a bubbling water feature, bathed in gentle sunlight from the skylight above. The center of the home, which is in many inter-terrace houses a dark and uncomfortable space, is here transformed into a lush internal garden. The front and the back facades of the 1st storey living spaces have been opened up to the maximum, using transparent roller shutters that can be hidden in the ceiling, allowing the prevailing winds to flow through the house. Surrounding this main living area are two external gardens at the front and back of the house. The front garden is a quaint chill-out space planted atop the car porch roof, creating a sensuous green backdrop for living room. The rear of the house has a small swimming pool directly outside the dining area that is nestled next to a textural boundary wall embedded with plants and ventilation blocks. These gardens and courtyard spaces of the home allow the occupants to feel the movement of the natural light across the house throughout the day, while shading them from its harsh impact. Several levels of tiered opened spaces can be seen while looking through the central courtyard - each planted with trees and creepers that lead the eye through the house, enhancing the views of the various spaces and greenery, and into the blue skies beyond.",
  },
  {
    id: "3",
    Code: "CSP",
    Name: "CURTAIN SYSTEMS PROJECT",
    Typology: "TOOL",
    Technology: "DYNAMO",
    Year: "2023",
    Status: "IDEA",
    Location: "NA",
    Description:
      "Representing 32% of the global population, Generation Z (those born between 1995 – 2010) accounts for a healthy chunk of the workforce (27% by 2025 and rising every year). These are the fresh young minds employers are fighting to attract. With prospective employers’ impact on society (93%) and a healthy work/life balance (77%) the two biggest motivators in deciding where Gen Z’ers want to work, a large part of any new office building’s design brief is green space. While hybrid working and flexible hours represent the most obvious ways to improve work/life balance for many, because of the missed social interactions and the lack of space or functionality at unproductive home workspaces, the majority of 16-24-year-olds are the only age group who prefer to work from the office. Architecture has always played a key role in providing shelter and protection for human beings. In prehistoric times, we sought refuge in caves, taking advantage of rock structures for protection against the natural elements and predators. Over time, shelters began to be made from materials found in nature, such as branches, leaves, and animal skins, evolving into more permanent and complex homes, with walls made of stone, bricks or wood, roofs to protect against rain and sun, and doors to control access. As we developed more advanced building skills, we used materials such as wood, stone, and clay and architecture evolved significantly, with the construction of temples, palaces, and fortifications that provided not only shelter but also symbolized power, status, and cultural identity. Even so, our buildings can continue to be seen as shells that protect us from the outside world. From the massive stones of Greek temples to glazed skyscrapers, we work with a range of possibilities and thicknesses to separate what we consider internal and external. This article seeks to explore this diversity of thicknesses in architecture, from simple materials to complex construction techniques, highlighting how this variation not only provides protection but also influences our perception and interaction with the built environment.",
  },
  {
    id: "4",
    Code: "MAM",
    Name: "MODERN ART MUSEUM",
    Typology: "MUSEUM",
    Technology: "RHINO",
    Year: "2018",
    Status: "INPROGRESS",
    Location: "PUNE",
    Description:
      "The set of proposed interventions does not want to be highlighted. The general objective is not to impose the face of the new, but to reveal in a new way what is already there, through articulations, spatial dispositions and new paths that the interventions discreetly provide. The emphasis of the new elements does not reside in their appearance, but in their performance, in what they are capable of promoting, in their effectiveness in dynamizing and enhancing the virtues of the preexisting ones. The first action plan focuses on works to recover the physical integrity and rehabilitation/modernization of the existing building, as well as the creation of a new, complementary and integrated sector, containing most of the services and areas necessary for the full functioning of a contemporary museum. We sought to conceive this expansion not as an annex or appendix, but as an underground extension of the pre-existing building which, in turn, opens up the possibility of connecting the Museum to the Park in a more powerful way and configures a new access esplanade, which extends all the way to Patriotas Street.",
  },
  {
    id: "5",
    Code: "WBH",
    Name: "WHITE BOX HOUSE",
    Typology: "HOUSING",
    Technology: "REVIT",
    Year: "2012",
    Status: "COMPLETED",
    Location: "BHUBANESWAR",
    Description:
      "This is a single-family house of 180m2 for a couple with two teenage children, located in a gated community within the city of Ezeiza in the Greater Buenos Aires region. The house is organized from 3 parallel walls of masonry and prefabricated wood panels that articulate the program of the house in the perpendicular direction. The walls adjust the privacy to the boundaries, generating its landscape characterized by the white-painted brickwork.",
  },
  {
    id: "6",
    Code: "MHC",
    Name: "MODULAR HOSPITAL CONCEPT",
    Typology: "HOSPITAL",
    Technology: "REVIT",
    Year: "2011",
    Status: "IDEA",
    Location: "BHUBANESWAR",
    Description:
      "University Hospital in Bergen is an ambitious vision for a comprehensive pediatric and women’s hospital, where all expertise related to children, youth, and women converges in a singular facility.",
  },
  {
    id: "7",
    Code: "HK9",
    Name: "HOUSE-K9",
    Typology: "HOUSING",
    Technology: "REVIT",
    Year: 2013,
    Status: "INPROGRESS",
    Location: "BANGALORE",
    Description:
      "The project started by choosing the land. The dream was a house between the woods, to interact with nature and make a childhood wish happen: A tree swing. We chose a land with these characteristics and adapted a project to preserve the topography and all the trees, creating a house set in the woods. Located in front of the condominium's internal lake, the house is designed to ensure a quick execution and can be used on weekends. It has little masonry and plenty of glass to bring nature and light into the environment. Cumaru wood and stone bricks enhance the natural elements that create harmony with the constant shade of the trees. The house has two suites, one of them, the main one, has a private garden. The living room and kitchen are integrated with the external patio, which brings another living room, a space that is the most used by the family. The toilet and pantry complete the spaces. The pool area was chosen to receive constant sun from the shade surrounding the house. Built in the second stage of work, it aims to bring family and children together. Inside, the highlight is personal design finds, pieces signed by Sérgio Rodrigues, and a resident’s Murano collection.",
  },
  {
    id: "8",
    Code: "CMR",
    Name: "CAPITAL MARKET REDEVELOPMENT",
    Typology: "URBAN REDEVELOPMENT",
    Technology: "REVIT",
    Year: 2009,
    Status: "IDEA",
    Location: "BHUBANESWAR",
    Description:
      "The historical local markets of San Lorenzo and Sant'Ambrogio in the centre of Florence, Italy, have been a meeting point for local people for decades; a privileged location from which a sense of community, belonging and sharing has grown. The structure-symbol for local residents and a major tourist attraction, they recently underwent a series of renovation works to update their image and strengthen relations with customers and retailers, with a view to preserving their identity and authenticity. With the restyling of these two indoor markets, the floors were renovated with the eco-active Active Surfaces® ceramics, chosen for their functionality, healthiness and sustainability. Both renovations were the work of the Florentine design firm S+S Studio and the architects Nicola Spagni and Diletta Storace, working with the Municipality of Florence, the Superintendence and the market traders. A complex and delicate joint work, the collective aim was to respect the historical values and local tradition, while at the same time restyling the market space to project it into the future.",
  },
  {
    id: "9",
    Code: "HM4",
    Name: "HOUSE-M4",
    Typology: "HOUSING",
    Technology: "REVIT",
    Year: 2013,
    Status: "COMPLETED",
    Location: "BHUBANESWAR",
    Description:
      "EcoBreeze House is a rare project with a relatively large design area, located in the heart of Ho Chi Minh City where houses are often closely built together. With this advantage, the design team aims to create a house that is closely connected to the nature and climate of Vietnam. Here, the house itself can 'breathe', creating a living space that is intimate with the surrounding environment. This project brings a fresh approach as the homeowners have chosen to use a steel structure instead of conventional reinforced concrete. Additionally, they desire to incorporate a significant amount of wood materials to create a harmonious living space with nature. We also pay great attention to the principles of feng shui. Specifically, the kitchen is positioned in a location without any other functional spaces above it and is tilted 45 degrees compared to the main direction of the house. To meet the homeowners' needs, this project has implemented an intelligent solution called the 'Double Skin Facade.' This structure consists of a thermal wood louver system (wood that has been thermally treated for increased durability) on the outside, combined with an inner sliding glass system. The entire system is securely fixed to a robust steel frame. It can be considered a two-in-one solution, addressing both the factors of sunlight and wind while incorporating the principles of feng shui. As a result, the house can fully demonstrate its 'breathable' characteristics.",
  },
  {
    id: "10",
    Code: "CCT",
    Name: "CONVENTION CENTRE THYSSEN KRUPP",
    Typology: "COMMERCIAL",
    Technology: "REVIT",
    Year: 2012,
    Status: "IDEA",
    Location: "ISTANBUL",
    Description:
      "Calgary’s BMO Centre at Stampede Park is ready to welcome the world, officially becoming Western Canada’s largest convention centre with the grand opening of its 565,000 sq. ft. expansion. Following decades of planning and four years of construction, the over 1M sq. ft. Tier 1 convention facility opens its doors for the first time, not only creating an architectural landmark for Calgary but making gatherings even greater with the ability to host a scale of convention the city hasn’t been able to previously accommodate. 'For four years, we have been promising that the expanded BMO Centre will offer Calgarians, southern Albertans and visitors to our city a greater way to gather. Today, it is with immeasurable pride that we open the doors to the BMO Centre at Stampede Park,' said Joel Cowley, CEO of the Calgary Stampede. 'The BMO Centre expansion was built for Calgary and southern Alberta, with the vision of creating a world-class facility both in terms of design and the ability to provide exceptional guest experiences through our signature western hospitality. With the interest we’ve seen from the meetings and conventions industry before the doors have even opened, we know that this facility is going to have a positive impact on Calgary’s economy by bolstering the tourism and hospitality sectors. We built this for our future, and we look forward to realizing the success of the expansion in the decades to come.' The expansion’s first major event, the Global Energy Show, is already loading into the expansion’s exhibition halls in preparation for their June 11 event, and there are another 500 conventions and events booked into the expansion post-opening to date. This also translates to filling restaurants, shops, rideshares and other attractions that make Calgary unique. The economic impact on Calgary will equate to approximately upwards of $100 million a year and provide thousands of jobs. The building, designed by leading design team Stantec, Populous and S2 Architecture, represents the next generation of convention facilities, one that promises best-in-class guest experience, boasts precedent-setting design architecture and serves as a gathering place for convention attendees and the local community alike. When we began design with our partners in 2019, we asked ourselves how we could design a facility that pushes the boundaries of convention centre design and experience, and every decision we made from that point on was with that goal in mind,' said Kate Thompson, President and CEO of Calgary Municipal Land Corporation, Development Manager for the project. 'CMLC is incredibly proud to have delivered this project on time and budget and to have delivered on the world-class promise we and our partners set out to achieve. With the completion of this catalyst project, we have set the tone for the coming years of development in The Culture + Entertainment District, and we are looking eagerly ahead to building on this momentum as we continue to transform this district together.'",
  },
  {
    id: "11",
    Code: "CCT",
    Name: "CONVENTION CENTRE THYSSEN KRUPP",
    Typology: "COMMERCIAL",
    Technology: "REVIT",
    Year: 2012,
    Status: "IDEA",
    Location: "ISTANBUL",
    Description:
      "Calgary’s BMO Centre at Stampede Park is ready to welcome the world, officially becoming Western Canada’s largest convention centre with the grand opening of its 565,000 sq. ft. expansion. Following decades of planning and four years of construction, the over 1M sq. ft. Tier 1 convention facility opens its doors for the first time, not only creating an architectural landmark for Calgary but making gatherings even greater with the ability to host a scale of convention the city hasn’t been able to previously accommodate. 'For four years, we have been promising that the expanded BMO Centre will offer Calgarians, southern Albertans and visitors to our city a greater way to gather. Today, it is with immeasurable pride that we open the doors to the BMO Centre at Stampede Park,' said Joel Cowley, CEO of the Calgary Stampede. 'The BMO Centre expansion was built for Calgary and southern Alberta, with the vision of creating a world-class facility both in terms of design and the ability to provide exceptional guest experiences through our signature western hospitality. With the interest we’ve seen from the meetings and conventions industry before the doors have even opened, we know that this facility is going to have a positive impact on Calgary’s economy by bolstering the tourism and hospitality sectors. We built this for our future, and we look forward to realizing the success of the expansion in the decades to come.' The expansion’s first major event, the Global Energy Show, is already loading into the expansion’s exhibition halls in preparation for their June 11 event, and there are another 500 conventions and events booked into the expansion post-opening to date. This also translates to filling restaurants, shops, rideshares and other attractions that make Calgary unique. The economic impact on Calgary will equate to approximately upwards of $100 million a year and provide thousands of jobs. The building, designed by leading design team Stantec, Populous and S2 Architecture, represents the next generation of convention facilities, one that promises best-in-class guest experience, boasts precedent-setting design architecture and serves as a gathering place for convention attendees and the local community alike. When we began design with our partners in 2019, we asked ourselves how we could design a facility that pushes the boundaries of convention centre design and experience, and every decision we made from that point on was with that goal in mind,' said Kate Thompson, President and CEO of Calgary Municipal Land Corporation, Development Manager for the project. 'CMLC is incredibly proud to have delivered this project on time and budget and to have delivered on the world-class promise we and our partners set out to achieve. With the completion of this catalyst project, we have set the tone for the coming years of development in The Culture + Entertainment District, and we are looking eagerly ahead to building on this momentum as we continue to transform this district together.'",
  },
  {
    id: "12",
    Code: "CCT",
    Name: "CONVENTION CENTRE THYSSEN KRUPP",
    Typology: "COMMERCIAL",
    Technology: "REVIT",
    Year: 2012,
    Status: "IDEA",
    Location: "ISTANBUL",
    Description:
      "Calgary’s BMO Centre at Stampede Park is ready to welcome the world, officially becoming Western Canada’s largest convention centre with the grand opening of its 565,000 sq. ft. expansion. Following decades of planning and four years of construction, the over 1M sq. ft. Tier 1 convention facility opens its doors for the first time, not only creating an architectural landmark for Calgary but making gatherings even greater with the ability to host a scale of convention the city hasn’t been able to previously accommodate. 'For four years, we have been promising that the expanded BMO Centre will offer Calgarians, southern Albertans and visitors to our city a greater way to gather. Today, it is with immeasurable pride that we open the doors to the BMO Centre at Stampede Park,' said Joel Cowley, CEO of the Calgary Stampede. 'The BMO Centre expansion was built for Calgary and southern Alberta, with the vision of creating a world-class facility both in terms of design and the ability to provide exceptional guest experiences through our signature western hospitality. With the interest we’ve seen from the meetings and conventions industry before the doors have even opened, we know that this facility is going to have a positive impact on Calgary’s economy by bolstering the tourism and hospitality sectors. We built this for our future, and we look forward to realizing the success of the expansion in the decades to come.' The expansion’s first major event, the Global Energy Show, is already loading into the expansion’s exhibition halls in preparation for their June 11 event, and there are another 500 conventions and events booked into the expansion post-opening to date. This also translates to filling restaurants, shops, rideshares and other attractions that make Calgary unique. The economic impact on Calgary will equate to approximately upwards of $100 million a year and provide thousands of jobs. The building, designed by leading design team Stantec, Populous and S2 Architecture, represents the next generation of convention facilities, one that promises best-in-class guest experience, boasts precedent-setting design architecture and serves as a gathering place for convention attendees and the local community alike. When we began design with our partners in 2019, we asked ourselves how we could design a facility that pushes the boundaries of convention centre design and experience, and every decision we made from that point on was with that goal in mind,' said Kate Thompson, President and CEO of Calgary Municipal Land Corporation, Development Manager for the project. 'CMLC is incredibly proud to have delivered this project on time and budget and to have delivered on the world-class promise we and our partners set out to achieve. With the completion of this catalyst project, we have set the tone for the coming years of development in The Culture + Entertainment District, and we are looking eagerly ahead to building on this momentum as we continue to transform this district together.'",
  },
];
